from typing import Protocol
from .contracts import TutoringPage, TutoringSnapshot

class TutoringRepository(Protocol):
    def get(self, identifier: str, actor_id: str) -> TutoringSnapshot | None: ...
    def list_for_owner(self, actor_id: str, cursor: str | None = None, limit: int = 50) -> TutoringPage: ...
