from typing import Protocol
from .contracts import LearnerPage, LearnerSnapshot

class LearnerRepository(Protocol):
    def get(self, identifier: str, actor_id: str) -> LearnerSnapshot | None: ...
    def list_for_owner(self, actor_id: str, cursor: str | None = None, limit: int = 50) -> LearnerPage: ...
