from typing import Protocol
from .contracts import InstitutionPage, InstitutionSnapshot

class InstitutionRepository(Protocol):
    def get(self, identifier: str, actor_id: str) -> InstitutionSnapshot | None: ...
    def list_for_owner(self, actor_id: str, cursor: str | None = None, limit: int = 50) -> InstitutionPage: ...
