from typing import Protocol
from .contracts import AssessmentPage, AssessmentSnapshot

class AssessmentRepository(Protocol):
    def get(self, identifier: str, actor_id: str) -> AssessmentSnapshot | None: ...
    def list_for_owner(self, actor_id: str, cursor: str | None = None, limit: int = 50) -> AssessmentPage: ...
