from typing import Protocol
from .contracts import CurriculumPage, CurriculumSnapshot

class CurriculumRepository(Protocol):
    def get(self, identifier: str, actor_id: str) -> CurriculumSnapshot | None: ...
    def list_for_owner(self, actor_id: str, cursor: str | None = None, limit: int = 50) -> CurriculumPage: ...
